# Generated by Django 5.1.1 on 2024-11-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterpretativeDecision',
            new_name='InterpretationDecision',
        ),
    ]
