# Generated by Django 5.1.1 on 2024-11-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_rename_interpretativedecision_interpretationdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='document',
            field=models.FileField(default=1, upload_to='laws/'),
            preserve_default=False,
        ),
    ]
