# Generated by Django 5.1.1 on 2024-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_law_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='codes/'),
        ),
        migrations.AlterField(
            model_name='law',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='laws/'),
        ),
    ]
