# Generated by Django 5.1.1 on 2024-11-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_code_document_alter_law_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretationdecision',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='interpretations/'),
        ),
        migrations.AlterField(
            model_name='interpretationdecision',
            name='category',
            field=models.CharField(choices=[('labor', 'Трудови'), ('family', 'Семейни')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interpretationdecision',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
