# Generated by Django 5.1.1 on 2024-11-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_bio_alter_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterpretativeDecision',
            new_name='InterpretationDecision',
        ),
    ]
