# Generated by Django 5.1.1 on 2024-11-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_interpretativedecision_interpretationdecision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='InterpretationDecision',
        ),
        migrations.DeleteModel(
            name='Law',
        ),
    ]
